import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import "../globals.css";
import SessionWrapper from "@/components/SessionWrapper";
import { Toaster } from "sonner";
const inter = Inter({ subsets: ["latin"] });
const plus_jakarta_san = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en" className="h-full">
        <body className={plus_jakarta_san.className + " " + "h-full"}>
          {children}
        </body>
        <Toaster richColors />
      </html>
    </SessionWrapper>
  );
}
