"""revision user_team ver 2

Revision ID: 2a61fc99ed39
Revises: 2f0047e05c9a
Create Date: 2024-07-28 16:54:09.305245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a61fc99ed39'
down_revision: Union[str, None] = '2f0047e05c9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE TYPE role AS ENUM ('admin', 'member')")
    op.execute("ALTER TABLE user_team_s ADD COLUMN role role")
    op.execute("CREATE TYPE access AS ENUM ('admin', 'view', 'edit', 'create', 'delete', 'approve', 'review' )")
    op.execute("ALTER TABLE user_team_s ADD COLUMN access access")            


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_team_s', 'access')
    op.drop_column('user_team_s', 'role')
    op.execute('DROP TYPE access')
    op.execute('DROP TYPE role')
    # ### end Alembic commands ###
