"""revision user_team

Revision ID: 2f0047e05c9a
Revises: 7eabb94b59a8
Create Date: 2024-07-28 16:49:33.979540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f0047e05c9a'
down_revision: Union[str, None] = '7eabb94b59a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('user_team_s', 'role',
    #            existing_type=postgresql.ENUM('view', 'edit', 'create', 'delete', 'approve', 'review', name='access'),
    #            type_=sa.Enum('admin', 'member', name='role'),
    #            existing_nullable=False)
    # op.alter_column('user_team_s', 'access',
    #            existing_type=postgresql.ENUM('admin', 'member', name='role'),
    #            type_=sa.Enum('admin', 'view', 'edit', 'create', 'delete', 'approve', 'review', name='access'),
    #            existing_nullable=False)
    op.drop_column('user_team_s', 'access')
    op.drop_column('user_team_s', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_team_s', 'access',
               existing_type=sa.Enum('admin', 'view', 'edit', 'create', 'delete', 'approve', 'review', name='access'),
               type_=postgresql.ENUM('admin', 'member', name='role'),
               existing_nullable=False)
    op.alter_column('user_team_s', 'role',
               existing_type=sa.Enum('admin', 'member', name='role'),
               type_=postgresql.ENUM('view', 'edit', 'create', 'delete', 'approve', 'review', name='access'),
               existing_nullable=False)
    # ### end Alembic commands ###
