"""update team invitation when user not registered

Revision ID: 45e745a3a78f
Revises: e1ef4f46a6f2
Create Date: 2024-08-16 03:50:51.838926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel 

# revision identifiers, used by Alembic.
revision: str = '45e745a3a78f'
down_revision: Union[str, None] = 'e1ef4f46a6f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_team_s', sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # op.alter_column('user_team_s', 'role',
    #            existing_type=postgresql.ENUM('admin', 'member', name='role'),
    #            nullable=False)
    # op.alter_column('user_team_s', 'access',
    #            existing_type=postgresql.ENUM('admin', 'view', 'edit', 'create', 'delete', 'approve', 'review', name='access'),
    #            nullable=False)
    op.create_index(op.f('ix_user_team_s_user_email'), 'user_team_s', ['user_email'], unique=False)
    op.create_foreign_key(None, 'user_team_s', 'users', ['user_email'], ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_team_s', type_='foreignkey')
    op.drop_index(op.f('ix_user_team_s_user_email'), table_name='user_team_s')
    # op.alter_column('user_team_s', 'access',
    #            existing_type=postgresql.ENUM('admin', 'view', 'edit', 'create', 'delete', 'approve', 'review', name='access'),
    #            nullable=True)
    # op.alter_column('user_team_s', 'role',
    #            existing_type=postgresql.ENUM('admin', 'member', name='role'),
    #            nullable=True)
    op.drop_column('user_team_s', 'user_email')
    # ### end Alembic commands ###
