"""remove user id from plan

Revision ID: 46e431f7e866
Revises: e2ea1e64e993
Create Date: 2024-09-10 03:49:19.421554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46e431f7e866'
down_revision: Union[str, None] = 'e2ea1e64e993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('plans_user_id_fkey', 'plans', type_='foreignkey')
    op.drop_column('plans', 'user_id')
    op.alter_column('user_team_s', 'role',
               existing_type=postgresql.ENUM('admin', 'member', name='role'),
               nullable=False)
    op.alter_column('user_team_s', 'access',
               existing_type=postgresql.ENUM('admin', 'view', 'edit', 'create', 'delete', 'approve', 'review', name='access'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_team_s', 'access',
               existing_type=postgresql.ENUM('admin', 'view', 'edit', 'create', 'delete', 'approve', 'review', name='access'),
               nullable=True)
    op.alter_column('user_team_s', 'role',
               existing_type=postgresql.ENUM('admin', 'member', name='role'),
               nullable=True)
    op.add_column('plans', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('plans_user_id_fkey', 'plans', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
