"""add is_feature_plan_active and description on table plan_feature

Revision ID: c1032b4540a2
Revises: 89bc7536ea58
Create Date: 2024-09-10 05:10:12.027296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'c1032b4540a2'
down_revision: Union[str, None] = '89bc7536ea58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_feature_s', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('plan_feature_s', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('plan_feature_s', sa.Column('is_feature_plan_active', sa.Boolean(), nullable=False))
    op.add_column('plan_feature_s', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_feature_s', 'description')
    op.drop_column('plan_feature_s', 'is_feature_plan_active')
    op.drop_column('plan_feature_s', 'updated_at')
    op.drop_column('plan_feature_s', 'created_at')
    # ### end Alembic commands ###
