"""add index for user_id within user_team_s table

Revision ID: cad5123fdfac
Revises: 2a61fc99ed39
Create Date: 2024-08-03 05:45:59.990157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cad5123fdfac'
down_revision: Union[str, None] = '2a61fc99ed39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('user_team_s', 'role',
    #            existing_type=postgresql.ENUM('admin', 'member', name='role'),
    #            nullable=False)
    # op.alter_column('user_team_s', 'access',
    #            existing_type=postgresql.ENUM('admin', 'view', 'edit', 'create', 'delete', 'approve', 'review', name='access'),
    #            nullable=False)
    op.create_index(op.f('ix_user_team_s_user_id'), 'user_team_s', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_team_s_user_id'), table_name='user_team_s')
    op.alter_column('user_team_s', 'access',
               existing_type=postgresql.ENUM('admin', 'view', 'edit', 'create', 'delete', 'approve', 'review', name='access'),
               nullable=True)
    op.alter_column('user_team_s', 'role',
               existing_type=postgresql.ENUM('admin', 'member', name='role'),
               nullable=True)
    # ### end Alembic commands ###
