"""add verification to user_team_s table

Revision ID: e1ef4f46a6f2
Revises: cad5123fdfac
Create Date: 2024-08-05 03:45:20.074691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1ef4f46a6f2'
down_revision: Union[str, None] = 'cad5123fdfac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_team_s', sa.Column('verified', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # op.alter_column('user_team_s', 'role',
    #            existing_type=postgresql.ENUM('admin', 'member', name='role'),
    #            nullable=False)
    # op.alter_column('user_team_s', 'access',
    #            existing_type=postgresql.ENUM('admin', 'view', 'edit', 'create', 'delete', 'approve', 'review', name='access'),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_team_s', 'access',
               existing_type=postgresql.ENUM('admin', 'view', 'edit', 'create', 'delete', 'approve', 'review', name='access'),
               nullable=True)
    op.alter_column('user_team_s', 'role',
               existing_type=postgresql.ENUM('admin', 'member', name='role'),
               nullable=True)
    op.drop_column('user_team_s', 'verified')
    # ### end Alembic commands ###
